apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - nginx-configmap.yaml
  - buildconfig.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: iso-share
