apiVersion: v1
kind: ConfigMap
metadata:
  name: iso-nginx-config
  labels:
    app: iso-share
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;
        root         /usr/share/nginx/html;
        index        index.html;

        location / {
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
            autoindex_format html;
            add_header Content-Disposition "inline";
        }

        location ~* \.(iso)$ {
            add_header Content-Disposition "attachment";
            add_header Content-Type application/octet-stream;
        }
    }
