apiVersion: v1
kind: Service
metadata:
  name: iso-share
  labels:
    app: iso-share
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: iso-share
  type: ClusterIP
